/*
 * Generated by erpcgen 1.9.0 on Wed Dec  7 08:24:49 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_remote_control_h_)
#define _remote_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief remote_control identifiers */
enum _remote_control_ids
{
    kremote_control_service_id = 1,
    kremote_control_remote_putc_id = 1,
    kremote_control_remote_locate_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name remote_control
//@{
int32_t remote_putc(int32_t c);

void remote_locate(int32_t column, int32_t row);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _remote_control_h_
