#
# Generated by erpcgen 1.9.0 on Wed Dec  7 08:24:52 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for remote_control
class Iremote_control(object):
    SERVICE_ID = 1
    REMOTE_PUTC_ID = 1
    REMOTE_LOCATE_ID = 2

    def remote_putc(self, c):
        raise NotImplementedError()

    def remote_locate(self, column, row):
        raise NotImplementedError()


